# docker-compose file managing Nginx and the application
# Loading some variables from the .env file:
#   - DOMAIN: DNS domain name
#   - EMAIL: Maintainer email
#   - APP_FOLDER: Directory containing the application
#   - FLASK_APP: Flask entrypoint
#   - FLASK_ENV: Flask environment

version: "3.2"

services:
  nginx:
    build:
      context: ./nginx
      args:
        DOMAINS: ${DOMAINS}
        FLASK: application
    ports:
      - 80:80
      - 443:443
    volumes:
      - "certshare:/shared"
    depends_on:
      - application
      - client

  application:
    build: ./${APP_FOLDER}
    command: gunicorn --bind 0.0.0.0:5000 --workers 3 ${FLASK_APP}:app
    environment:
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - 5000:5000

  client:
    build:
      context: ./client
      args:
        DOMAINS: ${DOMAINS}
    volumes:
      - "certshare:/shared"

volumes:
  certshare:
    driver: local
