# docker-compose file managing Nginx and the application
# Loading some variables from the .env file:
#   - DOMAIN: DNS domain name
#   - EMAIL: Maintainer email
#   - APP_FOLDER: Directory containing the application
#   - FLASK_APP: Flask entrypoint
#   - FLASK_ENV: Flask environment

version: "3.2"

services:
  nginx:
    build:
      context: ./nginx
      args:
        DOMAINS: ${DOMAINS}
        FLASK: application
    ports:
      - 80:80
      - 443:443
    volumes:
      - "certshare:/shared"
    networks:
      playground:
        ipv4_address: ${NGINX_IP}
    depends_on:
      - application
      - client

  application:
    build: ./${APP_FOLDER}
    command: gunicorn --bind 0.0.0.0:5000 --workers 3 ${FLASK_APP}:app
    environment:
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - 5000:5000
    networks:
      playground:
        ipv4_address: 172.25.0.12

  client:
    build:
      context: ./client
      args:
        DOMAINS: ${DOMAINS}
    environment:
      - DOMAINS=${DOMAINS}
      - NGINX_IP=${NGINX_IP}
    volumes:
      - "certshare:/shared"
      - ${PWD}/client/scripts:/pwscripts
    networks:
      playground:
        ipv4_address: 172.25.0.13

volumes:
  certshare:
    driver: local

networks:
  playground:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
